
OrdererOrgs:
  - Name: Orderer
    Domain: neXt.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: FF
    Domain: FF.neXt.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Clemson
    Domain: Clemson.neXt.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: SCN
    Domain: SCN.neXt.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1