version: "2"

networks:
  neXt:

services:

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - neXt

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - neXt

  peer0.Clemson.neXt.com:
    container_name: peer0.Clemson.neXt.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=ClemsonMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_neXt

      - CORE_PEER_ID=peer0.Clemson.neXt.com
      - CORE_PEER_ADDRESS=peer0.Clemson.neXt.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.Clemson.neXt.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Clemson.neXt.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.Clemson.neXt.com:10051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 9051:9051
    volumes:
      - ./crypto-config/peerOrganizations/Clemson.neXt.com/peers/peer0.Clemson.neXt.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/Clemson.neXt.com/peers/peer0.Clemson.neXt.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    extra_hosts:
      - "peer0.FF.neXt.com:34.125.125.1"
      - "peer0.SCN.neXt.com:34.125.125.1"
      - "orderer.neXt.com:34.125.125.1"
    networks:
      - neXt

  peer1.Clemson.neXt.com:
    container_name: peer1.Clemson.neXt.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=ClemsonMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_neXt

      - CORE_PEER_ID=peer1.Clemson.neXt.com
      - CORE_PEER_ADDRESS=peer1.Clemson.neXt.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.Clemson.neXt.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Clemson.neXt.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Clemson.neXt.com:9051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 10051:10051
    volumes:
      - ./crypto-config/peerOrganizations/Clemson.neXt.com/peers/peer1.Clemson.neXt.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/Clemson.neXt.com/peers/peer1.Clemson.neXt.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    extra_hosts:
      - "peer0.FF.neXt.com:34.125.125.1"
      - "peer0.SCN.neXt.com:34.125.125.1"
      - "orderer.neXt.com:34.125.125.1"
    networks:
      - neXt
