version: "2"

networks:
  neXt:

services:

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - neXt

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - neXt

  peer0.FF.neXt.com:
    container_name: peer0.FF.neXt.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=FFMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_neXt

      - CORE_PEER_ID=peer0.FF.neXt.com
      - CORE_PEER_ADDRESS=peer0.FF.neXt.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.FF.neXt.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.FF.neXt.com:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.FF.neXt.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb0
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/FF.neXt.com/peers/peer0.FF.neXt.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/FF.neXt.com/peers/peer0.FF.neXt.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    extra_hosts:
      - "peer0.Clemson.neXt.com:34.125.115.109"
      - "peer0.SCN.neXt.com:34.125.145.115"
      - "orderer.neXt.com:34.16.131.165"
    networks:
      - neXt

  peer1.FF.neXt.com:
    container_name: peer1.FF.neXt.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=FFMSP

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_neXt

      - CORE_PEER_ID=peer1.FF.neXt.com
      - CORE_PEER_ADDRESS=peer1.FF.neXt.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.FF.neXt.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.FF.neXt.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.FF.neXt.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/FF.neXt.com/peers/peer1.FF.neXt.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/FF.neXt.com/peers/peer1.FF.neXt.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    extra_hosts:
      - "peer0.Clemson.neXt.com:34.125.115.109"
      - "peer0.SCN.neXt.com:34.125.145.115"
      - "orderer.neXt.com:34.16.131.165"
    networks:
      - neXt

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.FF.neXt.com:7051
      - CORE_PEER_LOCALMSPID=FFMSP
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/FFMSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/FF.neXt.com/peers/peer0.FF.neXt.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/FF.neXt.com/peers/peer0.FF.neXt.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/FF.neXt.com/peers/peer0.FF.neXt.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/FF.neXt.com/users/Admin@FF.neXt.com/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    extra_hosts:
      - "peer0.FF.neXt.com:34.125.51.62"
      - "peer0.Clemson.neXt.com:34.125.115.109"
      - "peer0.SCN.neXt.com:34.125.145.115"
      - "orderer.neXt.com:34.16.131.165"
    networks:
      - neXt
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/FF.neXt.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/FF.neXt.com/
      - ./../vm2/crypto-config/peerOrganizations/Clemson.neXt.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/Clemson.neXt.com/
      - ./../vm3/crypto-config/peerOrganizations/SCN.neXt.com/:/etc/hyperledger/channel/crypto-config/peerOrganizations/SCN.neXt.com/
      - ./../vm4/crypto-config/ordererOrganizations/neXt.com/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/neXt.com/
