version: '2'

networks:
  neXt:

services:
  ca_SCN:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.SCN.neXt.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/SCN:/etc/hyperledger/fabric-ca-server
    container_name: ca.SCN.neXt.com
    hostname: ca.SCN.neXt.com
    networks:
      - neXt